version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/app/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
    - location: scripts/copy_jar_file.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user