version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
  AfterInstall:
    - location: scripts/install_dependencies.sh
    - location: scripts/copy_jar_file.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
