name: ci-cd-dev

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

permissions:
  checks: write # Check 권한
  pull-requests: write # Comment 권한

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      # 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # Gradle 빌드
      - name: Execute Gradle build
        run: ./gradlew clean build
      # 테스트 리포트 등록
      - name: Publish Test report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          fail_on_failure: true
      # Upload
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::590183807290:role/cd-role
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload AWS S3
        run: |
          aws s3 cp /build/libs/code-challenge-hub-0.0.1-SNAPSHOT.jar s3://${{ secrets.BUCKET_NAME }}/
